repos:
  - repo: https://github.com/thoughtworks/talisman
    rev: v1.11.0
    hooks:
      - id: talisman-commit
  - repo: https://github.com/punitlad/commiterator.git
    rev: v0.3.0
    hooks:
      - id: check-commit-message
        args: ["[API-[0-9]{4,}]"]
        stages: ["commit-msg"]
  - repo: https://github.com/punitlad/git-mob
    rev: f111493
    hooks:
      - id: add-coauthors
        stages: ["prepare-commit-msg"]
